<a href="https://colab.research.google.com/github/yootaka/AiQuest/blob/main/en4_8keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.datasets import mnist
from keras.utils import to_categorical

from keras.layers import Conv2D, MaxPool2D, Flatten, Dense
from keras.models import Sequential
from keras.models import load_model

import matplotlib.pyplot as plt
from PIL import Image
import os
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# Google ドライブをマウント
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
X = []
Y = []

folder_path = "/content/drive/My Drive/Colab Notebooks/AiQuest/en4/train/"
file_list = os.listdir(folder_path)

In [4]:
X_test = []
Y_test = []

folder_path_test = "/content/drive/My Drive/Colab Notebooks/AiQuest/en4/test/test/"
file_list_test = os.listdir(folder_path_test)

In [5]:
print(file_list) #ファイル確認

['bridge_000.jpeg', 'bridge_001.jpeg', 'bridge_003.jpeg', 'bridge_002.jpeg', 'bridge_005.jpeg', 'bridge_004.jpeg', 'bridge_006.jpeg', 'bridge_007.jpeg', 'bridge_009.jpeg', 'bridge_008.jpeg', 'bridge_011.jpeg', 'bridge_010.jpeg', 'bridge_013.jpeg', 'bridge_012.jpeg', 'bridge_014.jpeg', 'bridge_015.jpeg', 'bridge_016.jpeg', 'bridge_017.jpeg', 'bridge_018.jpeg', 'bridge_019.jpeg', 'bridge_020.jpeg', 'bridge_021.jpeg', 'bridge_022.jpeg', 'horn_000.jpeg', 'horn_001.jpeg', 'horn_002.jpeg', 'horn_003.jpeg', 'horn_006.jpeg', 'horn_005.jpeg', 'horn_004.jpeg', 'horn_007.jpeg', 'horn_008.jpeg', 'horn_009.jpeg', 'horn_010.jpeg', 'horn_011.jpeg', 'horn_013.jpeg', 'horn_012.jpeg', 'horn_014.jpeg', 'horn_015.jpeg', 'horn_017.jpeg', 'horn_016.jpeg', 'horn_018.jpeg', 'horn_019.jpeg', 'horn_020.jpeg', 'horn_022.jpeg', 'horn_021.jpeg', 'horn_023.jpeg', 'horn_025.jpeg', 'horn_024.jpeg', 'horn_026.jpeg', 'horn_027.jpeg', 'horn_028.jpeg', 'horn_029.jpeg', 'horn_030.jpeg', 'horn_031.jpeg', 'horn_033.jpeg', '

In [6]:
print(file_list_test) #ファイル確認

['120.jpeg', '197.jpeg', '053.jpeg', '137.jpeg', '051.jpeg', '062.jpeg', '173.jpeg', '059.jpeg', '177.jpeg', '128.jpeg', '203.jpeg', '187.jpeg', '029.jpeg', '151.jpeg', '006.jpeg', '068.jpeg', '150.jpeg', '113.jpeg', '202.jpeg', '211.jpeg', '191.jpeg', '025.jpeg', '033.jpeg', '176.jpeg', '109.jpeg', '139.jpeg', '037.jpeg', '103.jpeg', '045.jpeg', '091.jpeg', '024.jpeg', '146.jpeg', '088.jpeg', '110.jpeg', '101.jpeg', '081.jpeg', '072.jpeg', '013.jpeg', '094.jpeg', '115.jpeg', '212.jpeg', '189.jpeg', '038.jpeg', '004.jpeg', '061.jpeg', '055.jpeg', '162.jpeg', '052.jpeg', '122.jpeg', '111.jpeg', '102.jpeg', '116.jpeg', '209.jpeg', '083.jpeg', '049.jpeg', '074.jpeg', '080.jpeg', '160.jpeg', '188.jpeg', '071.jpeg', '067.jpeg', '123.jpeg', '148.jpeg', '100.jpeg', '075.jpeg', '205.jpeg', '035.jpeg', '011.jpeg', '019.jpeg', '093.jpeg', '182.jpeg', '012.jpeg', '200.jpeg', '106.jpeg', '207.jpeg', '028.jpeg', '079.jpeg', '170.jpeg', '125.jpeg', '031.jpeg', '086.jpeg', '172.jpeg', '147.jpeg', '15

In [7]:
image_size = 256
X = []
Y = []
for file in file_list:
    try:
        image = Image.open(folder_path + file)
    except:
        print('error', file)
        continue
    
    image = image.convert("RGB")
    image = image.resize((image_size, image_size))
    data = np.asarray(image)
    X.append(data)
    if 'bridge' in file:
        Y.append(1) #不良品
    elif 'horn' in file:
        Y.append(1) #不良品
    elif 'potato' in file:
        Y.append(1) #不良品
    else:
        Y.append(0) #良品

X_train = np.array(X) #画像データ
y_train = np.array(Y) #ラベルデータ

In [8]:
print(X_train.shape)
print(y_train.shape)

(289, 256, 256, 3)
(289,)


In [9]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [11]:
image_size = 256
X_test = []
Y_test = []
for file in file_list_test:
    try:
        image = Image.open(folder_path_test + file)
    except:
        print('error', file)
        continue
    
    image = image.convert("RGB")
    image = image.resize((image_size, image_size))
    data = np.asarray(image)
    X_test.append(data)
    if 'bridge' in file:
        Y_test.append(1) #不良品
    elif 'horn' in file:
        Y_test.append(1) #不良品
    elif 'potato' in file:
        Y_test.append(1) #不良品
    else:
         Y_test.append(file) #ファイル名
   
X_test = np.array(X_test) #画像データ
y_test = np.zeros([213,2]) #結果用配列
y_test_label = np.array(Y_test) #ラベルデータ

In [12]:
print(X_test.shape)
print(y_test.shape)
print(y_test_label.shape)

(213, 256, 256, 3)
(213, 2)
(213,)


In [13]:
y_test_label

array(['120.jpeg', '197.jpeg', '053.jpeg', '137.jpeg', '051.jpeg',
       '062.jpeg', '173.jpeg', '059.jpeg', '177.jpeg', '128.jpeg',
       '203.jpeg', '187.jpeg', '029.jpeg', '151.jpeg', '006.jpeg',
       '068.jpeg', '150.jpeg', '113.jpeg', '202.jpeg', '211.jpeg',
       '191.jpeg', '025.jpeg', '033.jpeg', '176.jpeg', '109.jpeg',
       '139.jpeg', '037.jpeg', '103.jpeg', '045.jpeg', '091.jpeg',
       '024.jpeg', '146.jpeg', '088.jpeg', '110.jpeg', '101.jpeg',
       '081.jpeg', '072.jpeg', '013.jpeg', '094.jpeg', '115.jpeg',
       '212.jpeg', '189.jpeg', '038.jpeg', '004.jpeg', '061.jpeg',
       '055.jpeg', '162.jpeg', '052.jpeg', '122.jpeg', '111.jpeg',
       '102.jpeg', '116.jpeg', '209.jpeg', '083.jpeg', '049.jpeg',
       '074.jpeg', '080.jpeg', '160.jpeg', '188.jpeg', '071.jpeg',
       '067.jpeg', '123.jpeg', '148.jpeg', '100.jpeg', '075.jpeg',
       '205.jpeg', '035.jpeg', '011.jpeg', '019.jpeg', '093.jpeg',
       '182.jpeg', '012.jpeg', '200.jpeg', '106.jpeg', '207.jp

データ整形

In [ ]:
####X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25)

In [29]:
# 画像をreshape
X_train = X_train.reshape(-1, image_size, image_size, 3)
X_test = X_test.reshape(-1, image_size, image_size, 3)

In [30]:

# 輝度値を0 ~ 1に入るように正規化
X_train = X_train.astype('float32')/255
X_test = X_test.astype('float32')/255

In [31]:
# one hot encoding
y_train = to_categorical(y_train) #2次元に
#y_test = to_categorical(y_test)

モデル作成

In [32]:
model_cnn = Sequential()
model_cnn.add(Conv2D(32, (3,3), activation='relu', input_shape=(image_size, image_size, 3)))
model_cnn.add(MaxPool2D(2,2))
model_cnn.add(Conv2D(64, (3,3), activation='relu'))
model_cnn.add(MaxPool2D(2,2))
model_cnn.add(Conv2D(128, (3,3), activation='relu'))
model_cnn.add(MaxPool2D(2,2))
model_cnn.add(Flatten())
model_cnn.add(Dense(512, activation='relu'))       
model_cnn.add(Dense(2, activation='softmax'))

model_cnn.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 254, 254, 32)      896       
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 127, 127, 32)      0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 125, 125, 64)      18496     
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 62, 62, 64)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 60, 60, 128)       73856     
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 30, 30, 128)       0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 115200)           

In [34]:
#学習プロセスの作成
model_cnn.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])
#学習
model_cnn.fit(X_train, y_train, epochs=10, batch_size=20)

#import tensorflow as tf

#train_data = tf.data.Dataset.from_tensor_slices((X_train, y_train))
#valid_data = tf.data.Dataset.from_tensor_slices((X_test, y_test))

#model_cnn.fit(train_data, epochs=10, validation_data=valid_data)

model_cnn.evaluate(X_test, y_test)

Epoch 1/10


ValueError: ignored

In [ ]:
result=model.predict(X_test, batch_size=None, verbose=0, steps=None)

In [ ]:
result

array([[0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 6.5287519e-17],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 3.6013436e-08],
       [1.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [6.8248606e-12, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 8.6457547e-26],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [3.4500782e-35, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [2.9659121e-08, 1.

In [ ]:
result[3]

array([1.000000e+00, 6.528752e-17], dtype=float32)

In [ ]:
#結果を1次元に変換
result2=np.argmax(result,axis=1)

In [ ]:
result2

array([1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
result3=np.vstack((y_test_label, result2))

In [ ]:
result3

array([['120.jpeg', '197.jpeg', '053.jpeg', '137.jpeg', '051.jpeg',
        '062.jpeg', '173.jpeg', '059.jpeg', '177.jpeg', '128.jpeg',
        '203.jpeg', '187.jpeg', '029.jpeg', '151.jpeg', '006.jpeg',
        '068.jpeg', '150.jpeg', '113.jpeg', '202.jpeg', '211.jpeg',
        '191.jpeg', '025.jpeg', '033.jpeg', '176.jpeg', '109.jpeg',
        '139.jpeg', '037.jpeg', '103.jpeg', '045.jpeg', '091.jpeg',
        '024.jpeg', '146.jpeg', '088.jpeg', '110.jpeg', '101.jpeg',
        '081.jpeg', '072.jpeg', '013.jpeg', '094.jpeg', '115.jpeg',
        '212.jpeg', '189.jpeg', '038.jpeg', '004.jpeg', '061.jpeg',
        '055.jpeg', '162.jpeg', '052.jpeg', '122.jpeg', '111.jpeg',
        '102.jpeg', '116.jpeg', '209.jpeg', '083.jpeg', '049.jpeg',
        '074.jpeg', '080.jpeg', '160.jpeg', '188.jpeg', '071.jpeg',
        '067.jpeg', '123.jpeg', '148.jpeg', '100.jpeg', '075.jpeg',
        '205.jpeg', '035.jpeg', '011.jpeg', '019.jpeg', '093.jpeg',
        '182.jpeg', '012.jpeg', '200.jpeg', '106

In [ ]:
#行列変換
result3_T = result3.T

In [ ]:
print(result3_T.shape)

(213, 2)


In [ ]:
result3_T

array([['120.jpeg', '1'],
       ['197.jpeg', '1'],
       ['053.jpeg', '1'],
       ['137.jpeg', '0'],
       ['051.jpeg', '1'],
       ['062.jpeg', '1'],
       ['173.jpeg', '0'],
       ['059.jpeg', '0'],
       ['177.jpeg', '1'],
       ['128.jpeg', '1'],
       ['203.jpeg', '1'],
       ['187.jpeg', '1'],
       ['029.jpeg', '0'],
       ['151.jpeg', '1'],
       ['006.jpeg', '1'],
       ['068.jpeg', '1'],
       ['150.jpeg', '1'],
       ['113.jpeg', '1'],
       ['202.jpeg', '1'],
       ['211.jpeg', '1'],
       ['191.jpeg', '1'],
       ['025.jpeg', '1'],
       ['033.jpeg', '1'],
       ['176.jpeg', '1'],
       ['109.jpeg', '1'],
       ['139.jpeg', '1'],
       ['037.jpeg', '1'],
       ['103.jpeg', '1'],
       ['045.jpeg', '1'],
       ['091.jpeg', '1'],
       ['024.jpeg', '1'],
       ['146.jpeg', '1'],
       ['088.jpeg', '1'],
       ['110.jpeg', '1'],
       ['101.jpeg', '1'],
       ['081.jpeg', '1'],
       ['072.jpeg', '0'],
       ['013.jpeg', '1'],
       ['094

In [ ]:
# 結果を張り付け、ファイル出力
#import pandas as pd
#sample= result3
#sample.to_csv("./drive/My Drive/Colab Notebooks/AiQuest/en4/submit01.csv",index=None,header=None,sep='\t')
#np.savetxt('./drive/My Drive/Colab Notebooks/AiQuest/en4/submit01.csv', result3_T,delimiter='\t')
#result3_T.to_csv('./drive/My Drive/Colab Notebooks/AiQuest/en4/submit01.csv',
#index=False,header=False,sep='\t')
#import pandas as pd
#prediction = pd.DataFrame(predictions, columns=['predictions']).to_csv('prediction.csv')
import csv
with open('./drive/My Drive/Colab Notebooks/AiQuest/en4/submit01.tsv', 'w') as f: #w:書き込み
#    writer = csv.writer(f, lineterminator='\n') # 改行コードを指定
    writer = csv.writer(f, delimiter='\t') # 改行コードを指定

    writer.writerows(result3_T) # 2次元配列の書き込み

In [ ]:
model.save('model.h5')