<a href="https://colab.research.google.com/github/yootaka/AiQuest/blob/main/en4_6keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.datasets import mnist
from keras.utils import to_categorical

from keras.layers import Dense
from keras.models import Sequential
from keras.models import load_model

import matplotlib.pyplot as plt
from PIL import Image
import os
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# Google ドライブをマウント
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
X = []
Y = []

folder_path = "/content/drive/My Drive/Colab Notebooks/AiQuest/en4/train/"
file_list = os.listdir(folder_path)

In [4]:
X_test = []
Y_test = []

folder_path_test = "/content/drive/My Drive/Colab Notebooks/AiQuest/en4/test/test/"
file_list_test = os.listdir(folder_path_test)

In [5]:
print(file_list) #ファイル確認

['bridge_000.jpeg', 'bridge_001.jpeg', 'bridge_003.jpeg', 'bridge_002.jpeg', 'bridge_005.jpeg', 'bridge_004.jpeg', 'bridge_006.jpeg', 'bridge_007.jpeg', 'bridge_009.jpeg', 'bridge_008.jpeg', 'bridge_011.jpeg', 'bridge_010.jpeg', 'bridge_013.jpeg', 'bridge_012.jpeg', 'bridge_014.jpeg', 'bridge_015.jpeg', 'bridge_016.jpeg', 'bridge_017.jpeg', 'bridge_018.jpeg', 'bridge_019.jpeg', 'bridge_020.jpeg', 'bridge_021.jpeg', 'bridge_022.jpeg', 'horn_000.jpeg', 'horn_001.jpeg', 'horn_002.jpeg', 'horn_003.jpeg', 'horn_006.jpeg', 'horn_005.jpeg', 'horn_004.jpeg', 'horn_007.jpeg', 'horn_008.jpeg', 'horn_009.jpeg', 'horn_010.jpeg', 'horn_011.jpeg', 'horn_013.jpeg', 'horn_012.jpeg', 'horn_014.jpeg', 'horn_015.jpeg', 'horn_017.jpeg', 'horn_016.jpeg', 'horn_018.jpeg', 'horn_019.jpeg', 'horn_020.jpeg', 'horn_022.jpeg', 'horn_021.jpeg', 'horn_023.jpeg', 'horn_025.jpeg', 'horn_024.jpeg', 'horn_026.jpeg', 'horn_027.jpeg', 'horn_028.jpeg', 'horn_029.jpeg', 'horn_030.jpeg', 'horn_031.jpeg', 'horn_033.jpeg', '

In [6]:
print(file_list_test) #ファイル確認

['120.jpeg', '197.jpeg', '053.jpeg', '137.jpeg', '051.jpeg', '062.jpeg', '173.jpeg', '059.jpeg', '177.jpeg', '128.jpeg', '203.jpeg', '187.jpeg', '029.jpeg', '151.jpeg', '006.jpeg', '068.jpeg', '150.jpeg', '113.jpeg', '202.jpeg', '211.jpeg', '191.jpeg', '025.jpeg', '033.jpeg', '176.jpeg', '109.jpeg', '139.jpeg', '037.jpeg', '103.jpeg', '045.jpeg', '091.jpeg', '024.jpeg', '146.jpeg', '088.jpeg', '110.jpeg', '101.jpeg', '081.jpeg', '072.jpeg', '013.jpeg', '094.jpeg', '115.jpeg', '212.jpeg', '189.jpeg', '038.jpeg', '004.jpeg', '061.jpeg', '055.jpeg', '162.jpeg', '052.jpeg', '122.jpeg', '111.jpeg', '102.jpeg', '116.jpeg', '209.jpeg', '083.jpeg', '049.jpeg', '074.jpeg', '080.jpeg', '160.jpeg', '188.jpeg', '071.jpeg', '067.jpeg', '123.jpeg', '148.jpeg', '100.jpeg', '075.jpeg', '205.jpeg', '035.jpeg', '011.jpeg', '019.jpeg', '093.jpeg', '182.jpeg', '012.jpeg', '200.jpeg', '106.jpeg', '207.jpeg', '028.jpeg', '079.jpeg', '170.jpeg', '125.jpeg', '031.jpeg', '086.jpeg', '172.jpeg', '147.jpeg', '15

In [34]:
image_size = 256
X = []
Y = []
for file in file_list:
    try:
        image = Image.open(folder_path + file)
    except:
        print('error', file)
        continue
    
    image = image.convert("RGB")
    image = image.resize((image_size, image_size))
    data = np.asarray(image)
    X.append(data)
    if 'bridge' in file:
        Y.append(1) #不良品
    elif 'horn' in file:
        Y.append(1) #不良品
    elif 'potato' in file:
        Y.append(1) #不良品
    else:
        Y.append(0) #良品

X_train = np.array(X) #画像データ
y_train = np.array(Y) #ラベルデータ

In [35]:
print(X_train.shape)
print(y_train.shape)

(289, 256, 256, 3)
(289,)


In [36]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [37]:
image_size = 256
X_test = []
Y_test = []
for file in file_list_test:
    try:
        image = Image.open(folder_path_test + file)
    except:
        print('error', file)
        continue
    
    image = image.convert("RGB")
    image = image.resize((image_size, image_size))
    data = np.asarray(image)
    X_test.append(data)
    if 'bridge' in file:
        Y_test.append(1) #不良品
    elif 'horn' in file:
        Y_test.append(1) #不良品
    elif 'potato' in file:
        Y_test.append(1) #不良品
    else:
         Y_test.append(file) #ファイル名
   
X_test = np.array(X_test) #画像データ
y_test = np.zeros([213,2]) #結果用配列
y_test_label = np.array(Y_test) #ラベルデータ

In [38]:
print(X_test.shape)
print(y_test.shape)
print(y_test_label.shape)

(213, 256, 256, 3)
(213, 2)
(213,)


In [39]:
y_test_label

array(['120.jpeg', '197.jpeg', '053.jpeg', '137.jpeg', '051.jpeg',
       '062.jpeg', '173.jpeg', '059.jpeg', '177.jpeg', '128.jpeg',
       '203.jpeg', '187.jpeg', '029.jpeg', '151.jpeg', '006.jpeg',
       '068.jpeg', '150.jpeg', '113.jpeg', '202.jpeg', '211.jpeg',
       '191.jpeg', '025.jpeg', '033.jpeg', '176.jpeg', '109.jpeg',
       '139.jpeg', '037.jpeg', '103.jpeg', '045.jpeg', '091.jpeg',
       '024.jpeg', '146.jpeg', '088.jpeg', '110.jpeg', '101.jpeg',
       '081.jpeg', '072.jpeg', '013.jpeg', '094.jpeg', '115.jpeg',
       '212.jpeg', '189.jpeg', '038.jpeg', '004.jpeg', '061.jpeg',
       '055.jpeg', '162.jpeg', '052.jpeg', '122.jpeg', '111.jpeg',
       '102.jpeg', '116.jpeg', '209.jpeg', '083.jpeg', '049.jpeg',
       '074.jpeg', '080.jpeg', '160.jpeg', '188.jpeg', '071.jpeg',
       '067.jpeg', '123.jpeg', '148.jpeg', '100.jpeg', '075.jpeg',
       '205.jpeg', '035.jpeg', '011.jpeg', '019.jpeg', '093.jpeg',
       '182.jpeg', '012.jpeg', '200.jpeg', '106.jpeg', '207.jp

データ整形

In [ ]:
####X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25)

In [40]:
# 画像を1次元配列にreshape
X_train = X_train.reshape(-1, image_size * image_size *3)
X_test = X_test.reshape(-1, image_size * image_size *3)

In [41]:

# 輝度値を0 ~ 1に入るように正規化
X_train = X_train.astype('float32')/255
X_test = X_test.astype('float32')/255

In [42]:
# one hot encoding
y_train = to_categorical(y_train) #2次元に
#y_test = to_categorical(y_test)

モデル作成

In [43]:
model = Sequential() #シーケンシャルモデル
model.add(Dense(64, activation='relu', input_dim=image_size * image_size *3)) #64のユニットを持つ層
model.add(Dense(2, activation='softmax')) #2のユニットで出力

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 64)                12582976  
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 130       
Total params: 12,583,106
Trainable params: 12,583,106
Non-trainable params: 0
_________________________________________________________________


In [57]:
#学習プロセスの作成
model.compile(optimizer='Adam',                 #アルゴリズム
              loss='categorical_crossentropy',  #損失関数
              metrics=['accuracy'])             #評価関数：正解率
#学習
model.fit(X_train, y_train, epochs=30, batch_size=40)

Epoch 1/30
8/8 [==============================] - 0s 15ms/step - loss: 33.6804 - accuracy: 0.5813
Epoch 2/30
8/8 [==============================] - 0s 16ms/step - loss: 16.8074 - accuracy: 0.4983
Epoch 3/30
8/8 [==============================] - 0s 15ms/step - loss: 12.7883 - accuracy: 0.6955
Epoch 4/30
8/8 [==============================] - 0s 15ms/step - loss: 8.8163 - accuracy: 0.5917
Epoch 5/30
8/8 [==============================] - 0s 16ms/step - loss: 3.4638 - accuracy: 0.6574
Epoch 6/30
8/8 [==============================] - 0s 15ms/step - loss: 1.5608 - accuracy: 0.7785
Epoch 7/30
8/8 [==============================] - 0s 16ms/step - loss: 1.0013 - accuracy: 0.8131
Epoch 8/30
8/8 [==============================] - 0s 17ms/step - loss: 0.7505 - accuracy: 0.7855
Epoch 9/30
8/8 [==============================] - 0s 15ms/step - loss: 0.2379 - accuracy: 0.9031
Epoch 10/30
8/8 [==============================] - 0s 15ms/step - loss: 0.1741 - accuracy: 0.9204
Epoch 11/30
8/8 [=========

In [58]:
model.evaluate(X_test, y_test)

7/7 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 0.5117


[0.0, 0.5117371082305908]

In [59]:
result=model.predict(X_test, batch_size=None, verbose=0, steps=None)

In [60]:
result

array([[6.82293787e-04, 9.99317765e-01],
       [1.56829908e-01, 8.43170047e-01],
       [1.56862494e-02, 9.84313726e-01],
       [9.98224556e-01, 1.77540921e-03],
       [3.11049121e-03, 9.96889532e-01],
       [1.06074177e-02, 9.89392638e-01],
       [9.99865770e-01, 1.34208050e-04],
       [1.35698840e-02, 9.86430168e-01],
       [5.95438965e-02, 9.40456092e-01],
       [9.95933115e-01, 4.06686077e-03],
       [1.24707446e-03, 9.98752952e-01],
       [3.42874020e-01, 6.57125950e-01],
       [8.22115481e-01, 1.77884489e-01],
       [7.44007289e-01, 2.55992651e-01],
       [1.16265327e-01, 8.83734703e-01],
       [4.95988905e-01, 5.04011095e-01],
       [8.40508699e-01, 1.59491315e-01],
       [8.93908436e-05, 9.99910593e-01],
       [1.81108132e-01, 8.18891883e-01],
       [6.26447871e-02, 9.37355161e-01],
       [5.41685402e-01, 4.58314598e-01],
       [2.10046366e-01, 7.89953649e-01],
       [9.24085617e-01, 7.59143531e-02],
       [3.73126343e-02, 9.62687314e-01],
       [4.465161

In [61]:
result[3]

array([0.99822456, 0.00177541], dtype=float32)

In [62]:
#結果を1次元に変換
result2=np.argmax(result,axis=1)

In [63]:
result2

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
result3=np.vstack((y_test_label, result2))

In [65]:
result3

array([['120.jpeg', '197.jpeg', '053.jpeg', '137.jpeg', '051.jpeg',
        '062.jpeg', '173.jpeg', '059.jpeg', '177.jpeg', '128.jpeg',
        '203.jpeg', '187.jpeg', '029.jpeg', '151.jpeg', '006.jpeg',
        '068.jpeg', '150.jpeg', '113.jpeg', '202.jpeg', '211.jpeg',
        '191.jpeg', '025.jpeg', '033.jpeg', '176.jpeg', '109.jpeg',
        '139.jpeg', '037.jpeg', '103.jpeg', '045.jpeg', '091.jpeg',
        '024.jpeg', '146.jpeg', '088.jpeg', '110.jpeg', '101.jpeg',
        '081.jpeg', '072.jpeg', '013.jpeg', '094.jpeg', '115.jpeg',
        '212.jpeg', '189.jpeg', '038.jpeg', '004.jpeg', '061.jpeg',
        '055.jpeg', '162.jpeg', '052.jpeg', '122.jpeg', '111.jpeg',
        '102.jpeg', '116.jpeg', '209.jpeg', '083.jpeg', '049.jpeg',
        '074.jpeg', '080.jpeg', '160.jpeg', '188.jpeg', '071.jpeg',
        '067.jpeg', '123.jpeg', '148.jpeg', '100.jpeg', '075.jpeg',
        '205.jpeg', '035.jpeg', '011.jpeg', '019.jpeg', '093.jpeg',
        '182.jpeg', '012.jpeg', '200.jpeg', '106

In [66]:
#行列変換
result3_T = result3.T

In [67]:
print(result3_T.shape)

(213, 2)


In [68]:
result3_T

array([['120.jpeg', '1'],
       ['197.jpeg', '1'],
       ['053.jpeg', '1'],
       ['137.jpeg', '0'],
       ['051.jpeg', '1'],
       ['062.jpeg', '1'],
       ['173.jpeg', '0'],
       ['059.jpeg', '1'],
       ['177.jpeg', '1'],
       ['128.jpeg', '0'],
       ['203.jpeg', '1'],
       ['187.jpeg', '1'],
       ['029.jpeg', '0'],
       ['151.jpeg', '0'],
       ['006.jpeg', '1'],
       ['068.jpeg', '1'],
       ['150.jpeg', '0'],
       ['113.jpeg', '1'],
       ['202.jpeg', '1'],
       ['211.jpeg', '1'],
       ['191.jpeg', '0'],
       ['025.jpeg', '1'],
       ['033.jpeg', '0'],
       ['176.jpeg', '1'],
       ['109.jpeg', '1'],
       ['139.jpeg', '0'],
       ['037.jpeg', '1'],
       ['103.jpeg', '1'],
       ['045.jpeg', '1'],
       ['091.jpeg', '1'],
       ['024.jpeg', '1'],
       ['146.jpeg', '1'],
       ['088.jpeg', '1'],
       ['110.jpeg', '0'],
       ['101.jpeg', '1'],
       ['081.jpeg', '1'],
       ['072.jpeg', '0'],
       ['013.jpeg', '0'],
       ['094

In [69]:
# 結果を張り付け、ファイル出力
#import pandas as pd
#sample= result3
#sample.to_csv("./drive/My Drive/Colab Notebooks/AiQuest/en4/submit01.csv",index=None,header=None,sep='\t')
#np.savetxt('./drive/My Drive/Colab Notebooks/AiQuest/en4/submit01.csv', result3_T,delimiter='\t')
#result3_T.to_csv('./drive/My Drive/Colab Notebooks/AiQuest/en4/submit01.csv',
#index=False,header=False,sep='\t')
#import pandas as pd
#prediction = pd.DataFrame(predictions, columns=['predictions']).to_csv('prediction.csv')
import csv
with open('./drive/My Drive/Colab Notebooks/AiQuest/en4/submit02.tsv', 'w') as f: #w:書き込み
#    writer = csv.writer(f, lineterminator='\n') # 改行コードを指定
    writer = csv.writer(f, delimiter='\t') # 改行コードを指定

    writer.writerows(result3_T) # 2次元配列の書き込み

In [126]:
model.save('model.h5')